apiVersion: v1
kind: ConfigMap
metadata:
  name: loci-api-config
  labels:
    app.kubernetes.io/name: loci-api
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
